services:
  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # AMQP protocol port
      - "15672:15672" # Management plugin UI port
    environment:
      RABBITMQ_DEFAULT_USER: admin         # Default user
      RABBITMQ_DEFAULT_PASS: admin         # Default password
      RABBITMQ_DEFAULT_VHOST: my_vhost     # Default virtual host
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq    # Persistent storage
      - rabbitmq_logs:/var/log/rabbitmq    # Logs

volumes:
  rabbitmq_data:
  rabbitmq_logs: