version: "3.8"

services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.3
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-cluster
      - cluster.initial_master_nodes=es01,es02,es03
      - discovery.seed_hosts=es02,es03
      - network.host=0.0.0.0
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - xpack.monitoring.collection.enabled=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    command: >
      bash -c "
      if [ ! -d /usr/share/elasticsearch/plugins/analysis-morfologik ]; then
        elasticsearch-plugin install --batch pl.allegro.tech.elasticsearch.plugin:elasticsearch-analysis-morfologik:8.15.3;
      fi &&
      if [ ! -d /usr/share/elasticsearch/plugins/analysis-stempel ]; then
        elasticsearch-plugin install --batch analysis-stempel;
      fi &&
      if [ ! -d /usr/share/elasticsearch/plugins/ltr ]; then
        elasticsearch-plugin install --batch https://github.com/o19s/elasticsearch-learning-to-rank/releases/download/v1.5.10-es8.15.3/ltr-plugin-v1.5.10-es8.15.3.zip;
      fi &&
      /bin/tini -- /usr/local/bin/docker-entrypoint.sh
      "

  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.3
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=es-cluster
      - cluster.initial_master_nodes=es01,es02,es03
      - discovery.seed_hosts=es01,es03
      - network.host=0.0.0.0
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - xpack.monitoring.collection.enabled=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata02:/usr/share/elasticsearch/data
    command: >
      bash -c "
      if [ ! -d /usr/share/elasticsearch/plugins/analysis-morfologik ]; then
        elasticsearch-plugin install --batch pl.allegro.tech.elasticsearch.plugin:elasticsearch-analysis-morfologik:8.15.3;
      fi &&
      if [ ! -d /usr/share/elasticsearch/plugins/analysis-stempel ]; then
        elasticsearch-plugin install --batch analysis-stempel;
      fi &&
      if [ ! -d /usr/share/elasticsearch/plugins/ltr ]; then
        elasticsearch-plugin install --batch https://github.com/o19s/elasticsearch-learning-to-rank/releases/download/v1.5.10-es8.15.3/ltr-plugin-v1.5.10-es8.15.3.zip;
      fi &&
      /bin/tini -- /usr/local/bin/docker-entrypoint.sh
      "

  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.3
    container_name: es03
    environment:
      - node.name=es03
      - cluster.name=es-cluster
      - cluster.initial_master_nodes=es01,es02,es03
      - discovery.seed_hosts=es01,es02
      - network.host=0.0.0.0
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - xpack.monitoring.collection.enabled=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata03:/usr/share/elasticsearch/data
    command: >
      bash -c "
      if [ ! -d /usr/share/elasticsearch/plugins/analysis-morfologik ]; then
        elasticsearch-plugin install --batch pl.allegro.tech.elasticsearch.plugin:elasticsearch-analysis-morfologik:8.15.3;
      fi &&
      if [ ! -d /usr/share/elasticsearch/plugins/analysis-stempel ]; then
        elasticsearch-plugin install --batch analysis-stempel;
      fi &&
      if [ ! -d /usr/share/elasticsearch/plugins/ltr ]; then
        elasticsearch-plugin install --batch https://github.com/o19s/elasticsearch-learning-to-rank/releases/download/v1.5.10-es8.15.3/ltr-plugin-v1.5.10-es8.15.3.zip;
      fi &&
      /bin/tini -- /usr/local/bin/docker-entrypoint.sh
      "

  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.3
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://es01:9200
    ports:
      - "5601:5601"
    depends_on:
      - es01
      - es02
      - es03

volumes:
  esdata01:
    driver: local
  esdata02:
    driver: local
  esdata03:
    driver: local
