

services:
  # Pierwszy klaster Elasticsearch
  elasticsearch_1:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.3
    container_name: elasticsearch_1
    environment:
      - cluster.name=elasticsearch-cluster-1
      - discovery.type=single-node
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200" # Port REST API Elasticsearch
      - "9300:9300" # Port transportowy
    volumes:
      - es_data_1:/usr/share/elasticsearch/data
    command: >
      bash -c "
      elasticsearch-plugin install --batch com.github.chytreg/elasticsearch-analysis-morfologik/2.3.1 &&
      elasticsearch-plugin install --batch analysis-stempel &&
      elasticsearch-plugin install --batch https://github.com/o19s/elasticsearch-learning-to-rank/releases/download/v1.5.4-es7.11.2/ltr-plugin-v1.5.10-es8.15.3.zip &
      /bin/tini -- /usr/local/bin/docker-entrypoint.sh
      "

  # Drugi klaster Elasticsearch
  elasticsearch_2:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.3
    container_name: elasticsearch_2
    environment:
      - cluster.name=elasticsearch-cluster-2
      - discovery.type=single-node
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9201:9200" # Port REST API Elasticsearch
      - "9301:9300" # Port transportowy
    volumes:
      - es_data_2:/usr/share/elasticsearch/data
    command: >
      bash -c "
      elasticsearch-plugin install --batch com.github.chytreg/elasticsearch-analysis-morfologik/2.3.1 &&
      elasticsearch-plugin install --batch analysis-stempel &&
      elasticsearch-plugin install --batch https://github.com/o19s/elasticsearch-learning-to-rank/releases/download/v1.5.4-es7.11.2/ltr-plugin-v1.5.10-es8.15.3.zip &
      /bin/tini -- /usr/local/bin/docker-entrypoint.sh
      "

  # Trzeci klaster Elasticsearch
  elasticsearch_3:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.3
    container_name: elasticsearch_3
    environment:
      - cluster.name=elasticsearch-cluster-3
      - discovery.type=single-node
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9202:9200" # Port REST API Elasticsearch
      - "9302:9300" # Port transportowy
    volumes:
      - es_data_3:/usr/share/elasticsearch/data
    command: >
      bash -c "
      elasticsearch-plugin install --batch com.github.chytreg/elasticsearch-analysis-morfologik/2.3.1 &&
      elasticsearch-plugin install --batch analysis-stempel &&
      elasticsearch-plugin install --batch https://github.com/o19s/elasticsearch-learning-to-rank/releases/download/v1.5.4-es7.11.2/ltr-plugin-v1.5.10-es8.15.3.zip &
      /bin/tini -- /usr/local/bin/docker-entrypoint.sh
      "

  # Kibana
  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.3
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch_1:9200,http://elasticsearch_2:9201,http://elasticsearch_3:9202
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch_1
      - elasticsearch_2
      - elasticsearch_3

volumes:
  es_data_1:
    driver: local
  es_data_2:
    driver: local
  es_data_3:
    driver: local
