version: "3.8"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    command: >
      bash -c "
      if [ ! -d /usr/share/elasticsearch/plugins/analysis-morfologik ]; then
        elasticsearch-plugin install --batch pl.allegro.tech.elasticsearch.plugin:elasticsearch-analysis-morfologik:8.15.3;
      fi &&
      if [ ! -d /usr/share/elasticsearch/plugins/analysis-stempel ]; then
        elasticsearch-plugin install --batch analysis-stempel;
      fi &&
      if [ ! -d /usr/share/elasticsearch/plugins/ltr ]; then
        elasticsearch-plugin install --batch https://github.com/o19s/elasticsearch-learning-to-rank/releases/download/v1.5.10-es8.15.3/ltr-plugin-v1.5.10-es8.15.3.zip;
      fi &&
      /bin/tini -- /usr/local/bin/docker-entrypoint.sh
      "

  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.3
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

volumes:
  es_data:
    driver: local