version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.3 # Możesz zmienić wersję na potrzebną
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false # Wyłączenie uwierzytelnienia dla uproszczenia
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g" # Ustawienia pamięci Java
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200" # Port REST API Elasticsearch
      - "9300:9300" # Port transportowy (dla komunikacji między węzłami)
    volumes:
      - es_data:/usr/share/elasticsearch/data
    command: >
      bash -c "
      elasticsearch-plugin install --batch com.github.chytreg/elasticsearch-analysis-morfologik/2.3.1 &&
      elasticsearch-plugin install --batch analysis-stempel &&
      elasticsearch-plugin install --batch https://github.com/o19s/elasticsearch-learning-to-rank/releases/download/v1.5.4-es7.11.2/ltr-plugin-v1.5.10-es8.15.3.zip &
      /bin/tini -- /usr/local/bin/docker-entrypoint.sh
      "

  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.3 # Dopasowana wersja Kibany
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200 # Adres Elasticsearch
    ports:
      - "5601:5601" # Port dla interfejsu Kibana
    depends_on:
      - elasticsearch

volumes:
  es_data:
    driver: local