
services:
  pulsar:
    image: apachepulsar/pulsar:4.0.3
    container_name: pulsar
    command: bin/pulsar standalone
    ports:
      - "6650:6650"   # Pulsar broker port
      - "8080:8080"   # Pulsar admin (web) port
    volumes:
      - ./pulsar_data:/pulsar/data
      - ./pulsar_conf:/pulsar/conf
