services:
  huggingface-server:
    build:
      context: .
    ports:
      - "5000:5000"
    environment:
      MODEL_ID:  "radlab/polish-sts-v2" # Replace with any BERT Hugging Face model ID that create vectors